### ISSUE TITLE
Problem with pgcache

### ISSUE THREAD

**Issue by hhkaos** [koopjs/koop-sample-app#22] opened 2015-06-22 21:07 UTC
Hi guys!, first of all congrats for this amazing project!

I have been trying to use it and I got a crack at koop-pgcache/index.js:354

```if (this.isNumeric(bbox.xmin) && this.isNumeric(bbox.xmax) &&
                           ^
TypeError: Cannot read property 'xmin' of undefined```

I was trying to display this in ArcGIS Online:
http://localhost:1337/github/chelm/geodata/colorado-tornadoes.geojson/FeatureServer/0

![screenshot 2015-06-22 23 02 02](https://cloud.githubusercontent.com/assets/826965/8293071/6b39ecae-1933-11e5-9b70-01826d4c6f4a.png)

**Comment by dmfenton** [comment] 2015-08-20 11:57
Hi @hhkaos sorry for the long delay. Are you still have this same issue?

**Comment by ngoldman** [comment] 2015-10-23 20:12
Closing as I haven't been able to reproduce and there have been significant updates to koop-pgcache and other dependencies since this issue.

**Closed by ngoldman** 2015-10-23 20:12 UTC

**Comment by hhkaos** [comment] 2015-10-24 15:24
Sorry, no. I solved it running this code on the database as you suggested @dmfenton 

```
CREATE TABLE "ckan:services" 
    ( id character varying(100), 
    host character varying(100) ) 
    WITH ( OIDS=FALSE ); 

ALTER TABLE "ckan:services" 
    OWNER TO yourUserName;
```

And sorry for my delay too.
Cheers,
Raul
